spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member_local?serverTimezone=Asia/Seoul
    username: do_local
    password: 1234

  hobbie-do:
    front-url: https://hobbie-do.site
  jwt:
    secret-key: thisIsTestKeyWillBeChangeSoonCommingSoon
    access-expire-time: 60000

springdoc:
  packages-to-scan: hobbiedo.member
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
